seo: 
  site_name: Technische Hilfe
  title: Technische Hilfe
  description:  Sie benötigen Hilfe mit Ihrem technische Gerät? Dann melden Sie sich bei mir!
  keywords: Klagenfurt, Villach, Hilfe, Telefon, Fernseher, Internet, Apple, Samsung, Windows, Drei, Magenta, A1, Tv Box, WPS, Kärnten, Software
  author: Daniel Brunner
social: 
  instagram_username:
  facebook_url:
  twitter_username: 
design:
  background_color: '#E1E3E3'
  footer_color: '#FFFBF9'
  dark-text_color: 'black'
  medium-text_color: 'rgb(90,90,95)'
  light-text_color: '#f7f5f3'
  featured-text_color: '#A0A8A7'
  dark_color: 'rgb(60,60,65)'
  medium_color: '#ede8e4'
  light_color: '#ECC7A4'
  v-light_color: '#FFFBF9'
  featured_color: '#B1B6B5'
  accent_color: 'rgb(167, 74, 74)'
